# Generated by Django 6.0 on 2026-01-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dateOfBirth",
            field=models.DateField(null=True),
        ),
    ]
